"""add_prolific_fields

Revision ID: 20260304075406
Revises: 20260226000000
Create Date: 2026-03-04 07:54:08.074971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '20260304075406'
down_revision: Union[str, Sequence[str], None] = '20260226000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('prolific_study_id', sa.String(length=128), nullable=True))
    op.add_column('experiments', sa.Column('prolific_completion_code', sa.String(length=64), nullable=True))
    op.add_column('experiments', sa.Column('prolific_study_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'prolific_study_status')
    op.drop_column('experiments', 'prolific_completion_code')
    op.drop_column('experiments', 'prolific_study_id')
    # ### end Alembic commands ###
